name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: AzBuilder/terrakube-action-github@0.2.2
      with:
        TERRAKUBE_TOKEN:  ${{ secrets.TERRAKUBE_PAT }} 
        TERRAKUBE_TEMPLATE: "Terraform-Plan"
        TERRAKUBE_REPOSITORY: "https://github.com/AzBuilder/terraform-sample-repository.git"
        TERRAKUBE_ENDPOINT: ${{ secrets.TERRAKUBE_GITPOD }}  # Needed to get PR information, if any
